### PR TITLE
More changes to make all systems load in sbcl

### PR DESCRIPTION
**Pull request by scymtym**
More changes to make all ASDF systems in the repository load successfully in SBCL. Definitely not mergable as-is this time.

### CODE REVIEW

**Comment by Bike** [comment]
very nice

The cleavir-env conditions should be removed completely, as they now live in cst-to-ast instead - unless something else is using them that I missed?

ast-to-source I haven't looked at or used in months, which is why it's rotten away

`the` using ctypes might take some work. Ctype integration may not be complete at all levels yet. I'll have to check that Clasp is hooked up correctly too.

**Comment by scymtym** [comment]
> The cleavir-env conditions should be removed completely, as they now live in cst-to-ast instead - unless something else is using them that I missed?

I added them (back, unknowingly) because the `cleavir-macroexpand-all` system uses them. I now changed the `cleavir-macroexpand-all` and `cleavir-generate-ast` systems to use the conditions defined in `cleavir-cst-to-ast` instead.

> ast-to-source I haven't looked at or used in months, which is why it's rotten away
>
> the using ctypes might take some work. Ctype integration may not be complete at all levels yet. I'll have to check that Clasp is hooked up correctly too.

Should I remove those commits for now?

**Comment by karlosz** [comment]
Another thing: I believe Generate-AST is now totally obsolete.

**Comment by scymtym** [comment]
> Another thing: I believe Generate-AST is now totally obsolete.

Do you recommend removing instead of fixing it?

**Comment by karlosz** [comment]
I don't think anything cares about Generate-AST so it should be fine to remove it.

**Comment by Bike** [comment]
yeah generate-ast has been obsolete for a while

I didn't know cleavir-macroexpand-all existed. https://github.com/s-expressionists/Cleavir/blob/master/Code-walker/Macroexpand-all/environment-query.lisp https://github.com/s-expressionists/Cleavir/blob/master/CST-to-AST/environment-query.lisp It looks to duplicate what CST-to-AST does, so if we want to keep it, it might actually be better to move everything back to cleavir-env. We could have versions of variable-info etc that signal and those that don't, maybe?

**Comment by Bike** [comment]
I have created a new "renovate" branch for making sure that everything in Cleavir is in use or at least working. So far I've just deleted some systems, but it would be good to e.g. define SSA or register allocation generically or at least in BIR terms. https://github.com/s-expressionists/Cleavir/tree/renovate

**Comment by scymtym** [comment]
Should I re-submit still relevant changes after the changes in the renovate branch go inter master or what is the best way to proceed?

**Comment by Bike** [comment]
Yeah, sorry, I'm kind of running with this a bit. I think waiting might be best - all the changes I'm making should eliminate some dependency problems and maybe add some.

**Comment by Bike** [comment]
Think I reached a decent stopping point with renovate. I'll make sure it still works in Clasp tomorrow, but now the only really broken systems should be in Code-walker/ and Path-replication/. dominance and liveness and loops and reaching-definitions and register-allocation and def-use-chains all at least load in sbcl, and dominance passes its tests.

**Comment by Bike** [comment]
alright, merged it. i see that caused some conflicts from stuff i deleted.

**Comment by scymtym** [comment]
I updated the changes, rebased and added a few more changes to make the test systems load.

**Pull request merged**
